### ISSUE TITLE
Uncaught TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by amsimoes** [ericblade/quagga2-react-example#10]
Hey all!

I'm getting this error just after the Scanner detecting the barcode (box drawn), and the screen goes white:
```
Uncaught TypeError: Cannot read property 'code' of undefined
    at eval (App.js?afc7:14)
    at Array.map (<anonymous>)
    at App (App.js?afc7:13)
    at renderWithHooks (react-dom.development.js?61bb:14797)
    at updateFunctionComponent (react-dom.development.js?61bb:17016)
    at beginWork (react-dom.development.js?61bb:18591)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:184)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:236)
    at invokeGuardedCallback (react-dom.development.js?61bb:289)
    at beginWork$1 (react-dom.development.js?61bb:23203)
```

Is this broken or is it specific to the Barcode I tried to scan?
Do I need to update something in the code?

Thanks!

**Comment by ericblade** [comment]
Hi !  It's entirely possible something is broken that I'm not aware of, this hasn't gone through particularly extensive testing. (my pc doesn't have a camera that is good enough to read barcodes... so since it requires standing up a server to reach with my phone, that's been a problem)  Have you made any changes to the code, or are you importing it into something else?  

 i have just pushed a change that would cause that line to not error if result is empty, but i'm not sure if result is supposed to be empty if it say finds a barcode but can't figure out what it is, or something.  Also updated dependencies, which might be a factor.

**Comment by amsimoes** [comment]
Hey @ericblade! 

Thanks for the quick input.
Actually it was giving the same error, problem was when trying to access `result.codeResult` and not `result`.

So I've changed App.js line 14 it to:
`{results.map((result) => (result.codeResult && <Result key={result.codeResult.code} result={result} />))}`

And it's working :)
It's printing the result codes on the page as it detects them.

As I stabilize and get closer to the webcam, it starts fixing and eventually displays the correct code, this is the normal behavior of the scanner right?

Shall I do a PR to fix this?

Thanks

**Comment by amsimoes** [comment]
Created #11 with this fix.

Also added info about deploying the demo :)

One issue I noted in iOS (my iPhone8, iOs 13) is that it only triggers the Camera permission on Safari. 
Chrome and Brave didn't work, showed play symbol with a slash.
Any hint about that?

**Comment by ericblade** [comment]
Yep, only Safari supports camera on iOS.  I'm not sure if the functions exist and don't work on Chrome and friends, or if getUserMedia is just not there... 

Thanks for the update, I'll merge it straight away.
