### ISSUE TITLE
Project doesn't start right away

### ISSUE THREAD

**Issue by FabioLugli** [ericblade/quagga2-react-example#8]
Thanks for the work on this repository, but if I use the 
`npm run start`
command, the project gives an error in Scanner.js, because it's used the validated variable, which is given by one of two possible definitons not implemented:

```if (result.codeResult && result.codeResult.code) {
                // const validated = barcodeValidator(result.codeResult.code);
                // const validated = validateBarcode(result.codeResult.code);
                // Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: validated ? 'green' : 'red', lineWidth: 3 });
                drawingCtx.font = "24px Arial";
                drawingCtx.fillStyle = validated ? 'green' : 'red';
                drawingCtx.fillText(`${result.codeResult.code} valid: ${validated}`, 10, 50);
                drawingCtx.fillText(result.codeResult.code, 10, 20);
                // if (validated) {
                //     onDetected(result);
                // }
            }````

Am I missing something on this barcodeValidator or validateBarcode function?

**Comment by ericblade** [comment]
hmm.. looking into that.

**Comment by ericblade** [comment]
... and this is why you should have your linters and code verifications all running on even small projects :-D

Thanks for pointing that out.  My personal code that I use in a private application that uses this has that, but i had just commented out the validate var, since i didn't implement the validate function here.  Oops! Didn't notice it being used again on the next line.

Should be good now.  Since my laptop camera isn't good enough to detect barcodes, I probably just ran it, saw a green box saying it almost detected one, and assumed it worked.

**Comment by FabioLugli** [comment]
Thanks for the quick fix!
